/* Create Foreign Key Constraints */

ALTER TABLE ab_core_us.ACU_TACUE ADD CONSTRAINT FK_ACU_TACUE_AU_TCOMPANY
	FOREIGN KEY (COMPANY_COMPANY) REFERENCES ab_core_us.ACU_TCOMPANY (COMPANY_COMPANY) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE ab_core_us.ACU_TCOMPANY ADD CONSTRAINT FK_ACU_TCOMPANY_ACU_TACCOUNT
	FOREIGN KEY (ACCOUNT_ACCOUNT) REFERENCES ab_core_us.ACU_ACCOUNT (ACCOUNT_ACCOUNT) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE ab_core_us.AU_TLOGIN ADD CONSTRAINT FK_AU_TLOGIN_AU_USER
	FOREIGN KEY (USER_USER) REFERENCES ab_core_us.AU_TUSER (USER_USER) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE ab_core_us.AU_TMEMBERSHIP ADD CONSTRAINT FK_AU_TMEMBERSHIP_ACU_COMPANY
	FOREIGN KEY (COMPANY_COMPANY) REFERENCES ab_core_us.ACU_TCOMPANY (COMPANY_COMPANY) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE ab_core_us.AU_TMEMBERSHIP ADD CONSTRAINT FK_AU_TMEMBERSHIP_AU_TROL	
	FOREIGN KEY (ROL_ROL) REFERENCES ab_core_us.AU_TROL (ROL_ROL) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE ab_core_us.AU_TMEMBERSHIP ADD CONSTRAINT FK_AU_TMEMBERSHIP_AU_USER
	FOREIGN KEY (USER_USER) REFERENCES ab_core_us.AU_TUSER (USER_USER) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE ab_core_us.CL_TCLIENT ADD CONSTRAINT FK_CL_TCLIENT_AU_TCOMPANY
	FOREIGN KEY (COMPANY_COMPANY) REFERENCES ab_core_us.ACU_TCOMPANY (COMPANY_COMPANY) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE ab_core_us.CL_TRECEIPT ADD CONSTRAINT FK_CL_TRECEIPT_CL_TCLIENT
	FOREIGN KEY (CLIENT_CLIENT) REFERENCES ab_core_us.CL_TCLIENT (CLIENT_CLIENT) ON DELETE No Action ON UPDATE No Action
;